pub mod alias;
pub mod cli;
pub mod config;
pub mod dirs;
pub mod display;
pub mod effects;
pub mod exchange;
pub mod hook;
pub mod import_export;
pub mod init;
pub mod messages;
pub mod profile;
pub mod project;
pub mod prompt;
pub mod security;
pub mod setup;
pub mod shell;
pub mod status;
pub mod trust;
pub mod update;

pub use alias::*;
pub use config::*;
pub use effects::*;
pub use exchange::*;
pub use messages::*;
pub use profile::*;
pub use project::*;
pub use update::UpdateError;

pub type Result<T> = anyhow::Result<T>;
