use indoc::formatdoc;
use log::info;

use crate::{
    dirs::{fish_config_dir, fish_functions_dir},
    Profile, TomlAlias,
};

pub fn init_shell_code(active_profile: &Profile) -> crate::Result<()> {
    let active_profile_name = &active_profile.name;

    let shell_code = indoc::indoc! {r#"
        # add the alias-manager functions folder to the fish functions path
        set fish_functions_path (path resolve $__fish_config_dir/functions/alias-manager/*/) $fish_function_path

        set -g _AM_ACTIVE_PROFILE "{active_profile_name}"

        # wrapper function to call the binary with taking care of callbacks etc.
        function am
            cargo run -p am -- $argv
        end

        function "am profile" --wraps='am profile' --description 'List all profiles'
            am profile $argv
            echo yes
        end

    "#};

    println!("{}", shell_code);

    Ok(())
}

pub fn setup_fish_config_file() -> crate::Result<()> {
    // in the fish config `conf.d` directory, we create a file that has wrappers to call the binary with taking care of callbacks etc.
    //
    // The file will be named `alias-manager.fish`
    let config_file = fish_config_dir().join("conf.d").join("alias-manager.fish");
    if !config_file.exists() {
        std::fs::create_dir_all(config_file.parent().unwrap())?;
    }

    // kudos to: https://www.reddit.com/r/fishshell/comments/176ahss/tip_you_can_use_function_subfolders_with_this/
    std::fs::write(
        &config_file,
        indoc::indoc! {r#"
            # add the alias-manager functions folder to the fish functions path
            set fish_functions_path (path resolve $__fish_config_dir/functions/alias-manager/*/) $fish_function_path
        "#},
    )?;

    Ok(())
}

pub fn setup_fish_functions_for_profile(profile: &Profile) -> crate::Result<()> {
    let profile_functions_dir = fish_functions_dir()
        .join("alias-manager")
        .join(profile.name.as_str());

    if !profile_functions_dir.exists() {
        std::fs::create_dir_all(&profile_functions_dir)?;
    }

    let Some(aliases) = profile.aliases.as_ref() else {
        info!("The provided profile `{}` has no aliases", profile.name);
        return Ok(());
    };

    let date = chrono::Local::now();
    for alias in aliases.iter() {
        let name = alias.0;
        let command = alias.1;
        let (command, description) = match &command {
            TomlAlias::Detailed(alias) => {
                let command = &alias.command;
                let description = alias.description.as_ref().unwrap_or(&command);
                (command, description)
            }
            TomlAlias::Command(command) => (&command.clone(), command),
        };
        let code = formatdoc! { r#"
            # Caution: This file is auto generated by `am env fish` at {date}
            #          Any changes made to this file will be lost
            function {name} --wraps='{command}' --description '{description}'
                {command} $argv
            end
        "#};

        let file = profile_functions_dir.join(format!("{name}.fish"));
        std::fs::write(&file, &code)?;

        println!("written to {}", file.display());
    }

    Ok(())
}
