use indoc::formatdoc;
use log::info;

use crate::{dirs::fish_functions_dir, Profile, TomlAlias};

pub fn init_shell_code(active_profile_name: &str) {
    let shell_code = formatdoc! {r#"
        # add the alias-manager functions folder to the fish functions path
        set fish_functions_path (path resolve $__fish_config_dir/functions/alias-manager/*/) $fish_function_path

        set -gx _AM_ACTIVE_PROFILE "{active_profile_name}"
        set -gx _AM_SHELL "fish"

        # Set up the session key that will be used to store logs
        # We don't use `random [min] [max]` because it is unavailable in older versions of fish shell
        set -gx _AM_SESSION_KEY (string sub -s1 -l16 (random)(random)(random)(random)(random)0000000000000000)

        # todo: remove this once am is stable
        # wrapper function to call the binary with taking care of callbacks etc.
        function am
            cargo run -p am -- $argv
        end

        am profile --print-full-init | source
    "#};

    println!("{shell_code}");
}

pub fn setup_fish_functions_for_profile(profile: &Profile) -> crate::Result<()> {
    let profile_functions_dir = fish_functions_dir()
        .join("alias-manager")
        .join(profile.name.as_str());

    if !profile_functions_dir.exists() {
        std::fs::create_dir_all(&profile_functions_dir)?;
    }

    let Some(aliases) = profile.aliases.as_ref() else {
        info!("The provided profile `{}` has no aliases", profile.name);
        return Ok(());
    };

    let date = chrono::Local::now();
    for alias in aliases.iter() {
        let name = alias.0;
        let command = alias.1;
        let (command, description) = match &command {
            TomlAlias::Detailed(alias) => {
                let command = &alias.command;
                let description = alias.description.as_ref().unwrap_or(&command);
                (command, description)
            }
            TomlAlias::Command(command) => (&command.clone(), command),
        };
        let code = formatdoc! { r#"
            # Caution: This file is auto generated by `am env fish` at {date}
            #          Any changes made to this file will be lost
            function {name} --wraps='{command}' --description '{description}'
                {command} $argv
            end
        "#};

        let file = profile_functions_dir.join(format!("{name}.fish"));
        std::fs::write(&file, &code)?;

        println!("written to {}", file.display());
    }

    Ok(())
}
